package com.app.enums;

public enum OrderStatus {
	PENDING,//By default
	CANCELLED, //From CUSTOMER
	ACCEPTED,PREPARING,REJECTED,READY_FOR_DELIVERY, //From MANAGER
	WAITING,ON_THE_WAY,DELIVERED // From DELIVERY 
}
