package com.app.enums;

public enum OrderStatus {
	PENDING,//By default
	CANCELLED, //From CUSTOMER
	ACCEPTED,REJECTED,PREPARING,READY_FOR_DELIVERY, //From MANAGER/RESTAURANT
	WAITING,ON_THE_WAY,DELIVERED // From DELIVERY 
}
