package com.app.enums;

public enum SubCategory {
	SOUTH_INDIAN, MAIN_COURSE, CHINESE, BEVERAGES, 
	DESSERTS, ADD_ONS, FAST_FOOD,APPETIZERS, 
	SALADS, SANDWICHES, BURGERS, PIZZAS, PASTA, WRAPS, RICE_BOWLS,
	CAKE, CHICKEN
}
